version: "3.6"

services:
  api:
    build: "."
    command: "api-service"
    depends_on:
      - "postgres"
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "task"
      POSTGRES_USER: "task"
      POSTGRES_PASSWORD: "123456"

  postgres:
    build: "./postgres"
    restart: "always"
    environment:
      POSTGRES_DB: "task"
      POSTGRES_USER: "task"
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
